version: "3.8"
services:

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - 3000:3000
    depends_on: 
      - mongodb
    command:
      node app.js

  mongodb:
    build:
      context: ./mongodb/
      dockerfile: Dockerfile
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  nginx-conf:
    build:
      context: ./nginx-conf/
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - app